alert("esto es una ventana emergente")
console.log("se agrega segunda version desde local")
console.log("se agrega cambio en rama pruebas")
console.log("segundos cambios en rama pruebas")
console.log("2181004")
console.log("taller tecnologico II")
console.log("Juan Felipe Valencia Rey")
